[package]
name = "latex-to-unicode-c-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "C ABI shared library for latex-to-unicode (for LuaJIT FFI in Neovim)."

[lib]
crate-type = ["cdylib"]

[dependencies]
latex-to-unicode = { path = "../core" }
